"""unique_phone_2_migration

Revision ID: b88b0c9c32d5
Revises: 1893efa8213c
Create Date: 2023-05-13 00:36:23.184960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88b0c9c32d5'
down_revision = '1893efa8213c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mechanics', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mechanics', type_='unique')
    # ### end Alembic commands ###
